---
kafka_bootstrap_servers: "REPLACE_WITH_BOOTSTRAP_ENDPOINT"
kafka_security_protocol: "SASL_SSL"
kafka_sasl_mechanism: "PLAIN"
kafka_api_key: "REPLACE_WITH_API_KEY"
kafka_api_secret: "REPLACE_WITH_API_SECRET"
